import type { Metadata } from 'next';

// Production origin (owner picked the domain 2026-07-31; verified available
// on .ge whois that day  register at an accredited nic.ge registrar before
// deploy). Absolute og:image / JSON-LD URLs bake this in at build time.
export const SITE_URL = 'https://galaktioni.ge';

export const SITE_NAME = 'თავის ქალა არტისტული ყვავილებით';

// Open Graph + Twitter card block for a page. Next.js replaces (not merges)
// the whole `openGraph` object per page, so every page passes through here
// to keep siteName/locale/dimensions consistent. `slug` is the page's folder
// under public/meta/ (generated by scripts/build-og.mjs).
export function socialMeta({
  title,
  description,
  slug,
}: {
  title: string;
  description?: string;
  slug: string;
}): Pick<Metadata, 'openGraph' | 'twitter'> {
  return {
    openGraph: {
      siteName: SITE_NAME,
      locale: 'ka_GE',
      type: 'website',
      title,
      ...(description && { description }),
      images: [{ url: `/meta/${slug}/og.jpg`, width: 1200, height: 630 }],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      images: [`/meta/${slug}/twitter.jpg`],
    },
  };
}

// schema.org images in the three aspect ratios Google rich results want
export function structuredImages(slug: string): string[] {
  return ['still.jpg', 'card.jpg', 'thumb.jpg'].map(
    (file) => `${SITE_URL}/meta/${slug}/${file}`,
  );
}
